// main
export const SET_LOADING = "SET_LOADING";

//BASIC INFORMATION
export const GET_BASIC_INFORMATION = "SET_BASIC_INFORMATION";
export const SET_BASIC_INFORMATION = "GET_BASIC_INFORMATION";

//EDUCATION
export const GET_DATA_EDUCATION = "SET_DATA_EDUCATION";
export const SET_DATA_EDUCATION = "GET_DATA_EDUCATION";

//EXPERIENCE
export const GET_DATA_EXPERIENCE = "SET_DATA_EXPERIENCE";
export const SET_DATA_EXPERIENCE = "GET_DATA_EXPERIENCE";
